### PR TITLE
Add bottle dependency and test script, 'Hello World'

### PR DESCRIPTION
**Pull request by beeankha**
This adds the Bottle dependency to the repo, as well as updating the `pipfile`.  There is a test script called `bottle_helloworld.py` that I used in order to see if Bottle is working.

Per instructions found here:
https://bottlepy.org/docs/dev/tutorial.html#installation

### CODE REVIEW

**Comment by beeankha** [comment]
Connected to issue https://github.com/benthomasson/bosc/issues/2

**Comment by beeankha** [comment]
Removed `bottle.py` and moved `bottle_helloworld.py` into `tests` directory per @benthomasson  instructions.

**Comment by beeankha** [comment]
@thedoubl3j according to the installation guide:

`The route() decorator binds a piece of code to a URL path. In this case, we link the /hello path to the hello() function. This is called a route (hence the decorator name) and is the most important concept of this framework. You can define as many routes as you want. Whenever a browser requests a URL, the associated function is called and the return value is sent back to the browser.
`

**Comment by thedoubl3j** [comment]
roger that @beeankha thanks!

**Pull request merged**
